### ISSUE TITLE
syscall: add support for v3

### ISSUE THREAD

**Issue by shoenig** [shoenig/go-landlock#34]
v3 add support for `LANDLOCK_ACCESS_FS_TRUNCATE` (not yet available in `x/sys/unix`)

Similar to how we conditionally enable _REFER

```
if version >= 2 {
  opts |= fsRefer
}
```

https://docs.kernel.org/userspace-api/landlock.html#file-truncation-abi-3

**Comment by l0kod** [comment]
Hi Seth,

FYI, this is already implemented in https://github.com/landlock-lsm/go-landlock.
You may have missed it but @gnoack is proposing a collaboration as described in #32. What do you think?
